# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: left_arm
  joint_model_group_pose: left_arm_home
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - arm_L_joint1
    - arm_L_joint2
    - arm_L_joint3
    - arm_L_joint4
    - arm_L_joint5
    - arm_L_joint6
    - arm_R_joint1
    - arm_R_joint2
    - arm_R_joint3
    - arm_R_joint4
    - arm_R_joint5
    - arm_R_joint6
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: left_arm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - arm_L_joint1
      - arm_L_joint2
      - arm_L_joint3
      - arm_L_joint4
      - arm_L_joint5
      - arm_L_joint6
  - name: right_arm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - arm_R_joint1
      - arm_R_joint2
      - arm_R_joint3
      - arm_R_joint4
      - arm_R_joint5
      - arm_R_joint6

left_arm_controller:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - arm_L_joint1
    - arm_L_joint2
    - arm_L_joint3
    - arm_L_joint4
    - arm_L_joint5
    - arm_L_joint6
#  gains:
#    arm_L_joint1: { p: 100, d: 1, i: 1, i_clamp: 1 }
#    arm_L_joint2: { p: 100, d: 1, i: 1, i_clamp: 1 }
#    arm_L_joint3: { p: 100, d: 1, i: 1, i_clamp: 1 }
#    arm_L_joint4: { p: 100, d: 1, i: 1, i_clamp: 1 }
#    arm_L_joint5: { p: 100, d: 1, i: 1, i_clamp: 1 }
#    arm_L_joint6: { p: 100, d: 1, i: 1, i_clamp: 1 }

right_arm_controller:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - arm_R_joint1
    - arm_R_joint2
    - arm_R_joint3
    - arm_R_joint4
    - arm_R_joint5
    - arm_R_joint6
#  gains:
#    arm_R_joint1: { p: 100, d: 1, i: 1, i_clamp: 1 }
#    arm_R_joint2: { p: 100, d: 1, i: 1, i_clamp: 1 }
#    arm_R_joint3: { p: 100, d: 1, i: 1, i_clamp: 1 }
#    arm_R_joint4: { p: 100, d: 1, i: 1, i_clamp: 1 }
#    arm_R_joint5: { p: 100, d: 1, i: 1, i_clamp: 1 }
#    arm_R_joint6: { p: 100, d: 1, i: 1, i_clamp: 1 }