# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  arm_L_joint1:
    has_velocity_limits: true
    max_velocity: 8.380000000000001
    has_acceleration_limits: false
    max_acceleration: 0
  arm_L_joint2:
    has_velocity_limits: true
    max_velocity: 8.029999999999999
    has_acceleration_limits: false
    max_acceleration: 0
  arm_L_joint3:
    has_velocity_limits: true
    max_velocity: 9.08
    has_acceleration_limits: false
    max_acceleration: 0
  arm_L_joint4:
    has_velocity_limits: true
    max_velocity: 9.77
    has_acceleration_limits: false
    max_acceleration: 0
  arm_L_joint5:
    has_velocity_limits: true
    max_velocity: 9.77
    has_acceleration_limits: false
    max_acceleration: 0
  arm_L_joint6:
    has_velocity_limits: true
    max_velocity: 15.71
    has_acceleration_limits: false
    max_acceleration: 0